// tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Light mode design tokens (matching tokens.ts and Discover/SignUp)
        bg: '#F6F5FB',
        surface: '#FFFFFF',
        'surface-muted': '#EFEDF7',
        'surface-hover': '#F0EFF8',
        field: '#FAF9FE',
        text: '#1B1730',
        'text-secondary': '#4E4966',
        'text-muted': '#6A6482',
        'text-subtle': '#857F9C',
        border: '#E3E0EF',
        'border-strong': '#CFCADF',

        // Brand colors (Campusly Violet)
        brand: '#5B3FD1',
        'brand-pressed': '#4A31AE',
        'brand-soft': '#EEEAFF',
        'brand-dark': '#7357E6',
        'brand-soft-dark': '#251C4D',
        primary: '#5B3FD1',
        'primary-pressed': '#4A31AE',
        'primary-soft': '#EEEAFF',
        'accent-start': '#2B1D66',
        'accent-mid': '#43299F',
        'accent-end': '#5B3FD1',
        violet: '#7F63EA',
        'violet-soft': '#EEEAFF',
        ink: '#1B1730',
        presence: '#34D399',

        // Post types & semantics
        ocean: '#0F7A56',
        'ocean-soft': '#E1F6EE',
        'ocean-deep': '#064E3B',
        sun: '#D97706',
        'sun-soft': '#FEF3D7',
        berry: '#C8344F',
        'berry-soft': '#FDECEF',
        success: '#0F7A56',
        'success-soft': '#E1F6EE',
        danger: '#C8344F',
        'danger-soft': '#FDECEF',
        warning: '#B45309',
        'warning-soft': '#FEF3D7',
        info: '#2563B8',
        'info-soft': '#E7F0FC',
        mist: '#F6F5FB',
        'message-out': '#EEEAFF',
        'message-in': '#FFFFFF',

        // Special post cards (from draft mockups)
        opportunity: '#0F7A56',
        'opportunity-banner': '#064E3B',
        'opportunity-accent': '#10B981',
        'opportunity-soft': '#E1F6EE',
        achievement: '#B45309',
        'achievement-banner': '#F59E0B',
        'achievement-accent': '#FBBF24',
        'achievement-soft': '#FEF3D7',
        event: '#C2410C',
        'event-banner': '#3B1C0B',
        'event-accent': '#EA580C',
        'event-soft': '#FFEDD5',

        // Dark mode variants (used via dark: prefix)
        'bg-dark': '#0E0B1C',
        'surface-dark': '#171229',
        'surface-muted-dark': '#1F1936',
        'surface-hover-dark': '#251C4D',
        'field-dark': '#1C1632',
        'text-dark': '#F5F2FF',
        'text-secondary-dark': '#D3CCEB',
        'text-muted-dark': '#A59EC3',
        'text-subtle-dark': '#8278A8',
        'border-dark': '#2E2650',
        'border-strong-dark': '#40366B',
        'message-out-dark': '#31265F',
        'message-in-dark': '#171229',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
        display: ['SpaceGrotesk', 'Inter', 'ui-sans-serif', 'system-ui'],
      },
      borderRadius: {
        '4xl': '2rem',
      },
    },
  },
  plugins: [],
};
