import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { ThemedText } from '@/ui/ThemedText';
import { EmptyStateAnimation } from '@/ui/EmptyStateAnimation';
import { useAuth } from '@/lib/auth/AuthContext';
import { usePermissions } from '@/hooks/usePermissions';
import { fetchTeacherClasses } from '@/lib/api/teacherMarks';
import type { TeacherClass } from '@/lib/types/teacherMarks';

/** Same conversation-list visual language as student courses. */
export default function TeacherCoursesScreen() {
  const router = useRouter(); const { accessToken } = useAuth(); const { hasPermission } = usePermissions(); const [classes, setClasses] = useState<TeacherClass[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async (refresh = false) => { if (!accessToken) return; refresh ? setRefreshing(true) : setLoading(true); try { setClasses(await fetchTeacherClasses(accessToken)); } catch (error) { console.error('[Teacher courses] load failed', error); } finally { setLoading(false); setRefreshing(false); } }, [accessToken]); useEffect(() => { void load(); }, [load]);
  return <ScrollView className="flex-1 bg-bg dark:bg-bg-dark" contentContainerStyle={{ paddingTop: 12, paddingBottom: 36, flexGrow: 1 }} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor="#5b3fd1" />}><View className="px-5 pb-3"><ThemedText variant="display">Courses</ThemedText><ThemedText variant="caption" className="text-text-muted dark:text-text-muted-dark mt-1">Your class channels and teaching updates</ThemedText></View>{loading ? <ActivityIndicator color="#5b3fd1" className="py-20" /> : !classes.length ? <EmptyStateAnimation icon="book-outline" title="No assigned courses" subtitle="Your teaching assignments will appear here." /> : classes.map((item) => <TouchableOpacity key={item.id} activeOpacity={.78} onPress={() => router.push(`/teacher/courses/${item.course_id}?name=${encodeURIComponent(item.course_name)}&classId=${item.id}` as any)} className="mx-4 px-3 py-4 flex-row border-b border-border dark:border-border-dark" accessibilityRole="button" accessibilityLabel={`Open ${item.course_name} course channel`}><View className="w-14 h-14 rounded-full bg-primary-soft items-center justify-center"><ThemedText variant="subheading" className="text-primary">{item.course_code.slice(0, 1).toUpperCase()}</ThemedText></View><View className="flex-1 ml-3 justify-center"><View className="flex-row justify-between"><ThemedText variant="body" className="font-bold flex-1" numberOfLines={1}>{item.course_name}</ThemedText><ThemedText variant="tiny" className="text-text-muted dark:text-text-muted-dark ml-2">{item.section}</ThemedText></View><ThemedText variant="caption" className="text-text-muted dark:text-text-muted-dark mt-1" numberOfLines={1}>{item.course_code} · {item.enrolled_count} students · Course channel</ThemedText></View><Ionicons name="chevron-forward" size={18} color="#9892aa" style={{ alignSelf: 'center' }} /></TouchableOpacity>)}{hasPermission('start_attendance') && classes.length > 0 ? <TouchableOpacity onPress={() => { const item = classes[0]; router.push(`/teacher/attendance/configure?classId=${item.id}&courseId=${item.course_id}&courseName=${encodeURIComponent(item.course_name)}` as any); }} className="mx-5 mt-5 rounded-2xl bg-primary py-4 flex-row items-center justify-center"><Ionicons name="checkmark-circle-outline" color="#fff" size={20} /><ThemedText variant="body" className="text-white font-semibold ml-2">Start attendance</ThemedText></TouchableOpacity> : null}</ScrollView>;
}
