import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Modal, RefreshControl, ScrollView, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { ThemedText } from '@/ui/ThemedText';
import { EmptyStateAnimation } from '@/ui/EmptyStateAnimation';
import { showToast } from '@/ui/Toast';
import { useAuth } from '@/lib/auth/AuthContext';
import { createMarkSubmission, deleteMarkSubmission, fetchClassMarkSubmissions, fetchTeacherClasses } from '@/lib/api/teacherMarks';
import { fetchAttendanceRoster, fetchAttendanceSessions } from '@/lib/api/attendance';
import type { MarkAssessmentType, TeacherClass, TeacherMarkSubmission } from '@/lib/types/teacherMarks';
import type { AttendanceRosterStudent, AttendanceSessionSummary } from '@/lib/types/attendance';

const TYPES: MarkAssessmentType[] = ['quiz', 'assignment', 'project', 'exam'];
const percent = (score: number, max: number) => max ? Math.round((score / max) * 100) : 0;

export default function TeacherMarksScreen() {
  const { accessToken } = useAuth(); const [classes, setClasses] = useState<TeacherClass[]>([]); const [selected, setSelected] = useState<TeacherClass | null>(null); const [submissions, setSubmissions] = useState<TeacherMarkSubmission[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [composer, setComposer] = useState(false); const [editing, setEditing] = useState<TeacherMarkSubmission | null>(null);
  const load = useCallback(async (refresh = false) => { if (!accessToken) return; setRefreshing(refresh); try { const classList = await fetchTeacherClasses(accessToken); setClasses(classList); const target = selected && classList.some((item) => item.id === selected.id) ? selected : classList[0] ?? null; setSelected(target); setSubmissions(target ? await fetchClassMarkSubmissions(target.id, accessToken) : []); } catch (error) { const message = error instanceof Error ? error.message : 'Could not load marks'; console.error('[Marks] Load failed', { message, error }); showToast.error('Marks unavailable', message); } finally { setLoading(false); setRefreshing(false); } }, [accessToken, selected]);
  useEffect(() => { const task = setTimeout(() => void load(), 0); return () => clearTimeout(task); }, [load]);
  const choose = async (course: TeacherClass) => { if (!accessToken) return; setSelected(course); try { setSubmissions(await fetchClassMarkSubmissions(course.id, accessToken)); } catch (error) { showToast.error('Could not load course marks', error instanceof Error ? error.message : 'Try again'); } };
  const removeAssessment = (submission: TeacherMarkSubmission) => { if (!accessToken) return; Alert.alert('Delete assessment?', 'This removes its recorded marks. Approved assessments cannot be deleted.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => { void deleteMarkSubmission(submission.id, accessToken).then(() => load(true)).catch((error: Error) => showToast.error('Could not delete assessment', error.message)); } }]); };
  return <ScrollView className="flex-1 bg-mist dark:bg-bg-dark" contentContainerStyle={{ padding: 20, paddingBottom: 44 }} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor="#0f766e" />}>
    <View className="flex-row justify-between items-center mb-5"><View><ThemedText variant="display">Marks</ThemedText><ThemedText variant="caption" className="text-text-muted dark:text-text-muted-dark mt-1">Enter raw marks; deductions remain visible and traceable.</ThemedText></View><TouchableOpacity accessibilityRole="button" accessibilityLabel="Create mark submission" onPress={() => setComposer(true)} className="w-11 h-11 rounded-2xl bg-ocean items-center justify-center"><Ionicons name="add" size={25} color="#fff" /></TouchableOpacity></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} className="mb-5"><View className="flex-row gap-2">{classes.map((item) => <TouchableOpacity key={item.id} onPress={() => void choose(item)} className={`rounded-2xl px-4 py-3 ${selected?.id === item.id ? 'bg-ink' : 'bg-surface dark:bg-surface-dark border border-border dark:border-border-dark'}`}><ThemedText variant="caption" className={selected?.id === item.id ? 'text-white font-bold' : ''}>{item.course_code} · {item.section}</ThemedText><ThemedText variant="tiny" className={selected?.id === item.id ? 'text-slate-300' : ''}>{item.enrolled_count} students</ThemedText></TouchableOpacity>)}</View></ScrollView>
    {loading ? <View className="py-20 items-center"><ActivityIndicator color="#6846dc" /></View> : !selected ? <EmptyStateAnimation icon="book-outline" title="No assigned courses" subtitle="Your assigned course sections will appear here." /> : submissions.length ? submissions.map((submission) => { const graded = submission.entries.length; const average = graded ? Math.round(submission.entries.reduce((sum, entry) => sum + percent(entry.final_score, submission.max_score), 0) / graded) : 0; return <View key={submission.id} className="rounded-3xl bg-surface dark:bg-surface-dark border border-border dark:border-border-dark p-5 mb-3"><View className="flex-row items-start"><View className="w-11 h-11 rounded-2xl bg-ocean-soft items-center justify-center"><Ionicons name="create-outline" size={22} color="#6846dc" /></View><View className="flex-1 ml-3"><ThemedText variant="subheading">{submission.assessment_name}</ThemedText><ThemedText variant="tiny">{submission.assessment_type} · /{submission.max_score} · {submission.status.replace('_', ' ')}</ThemedText></View><View className="items-end"><ThemedText variant="heading" className="text-ocean">{average}%</ThemedText><ThemedText variant="tiny">class avg.</ThemedText></View></View><View className="flex-row mt-4 pt-3 border-t border-border dark:border-border-dark"><ThemedText variant="caption" className="flex-1">{graded}/{selected.enrolled_count} graded</ThemedText><ThemedText variant="caption">Raw − deduction = final</ThemedText></View></View>; }) : <EmptyStateAnimation icon="ribbon-outline" title="No mark submissions" subtitle="Create an assessment to enter marks for this class." />}
    <GradeComposer visible={composer} course={selected} accessToken={accessToken} onClose={() => setComposer(false)} onCreated={() => void load(true)} />
  </ScrollView>;
}

function GradeComposer({ visible, course, accessToken, onClose, onCreated }: { visible: boolean; course: TeacherClass | null; accessToken: string | null; onClose: () => void; onCreated: () => void }) {
  const [title, setTitle] = useState(''); const [type, setType] = useState<MarkAssessmentType>('quiz'); const [maxScore, setMaxScore] = useState('20'); const [roster, setRoster] = useState<AttendanceRosterStudent[]>([]); const [sessions, setSessions] = useState<AttendanceSessionSummary[]>([]); const [attendanceSessionId, setAttendanceSessionId] = useState<string | undefined>(); const [scores, setScores] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!visible || !course || !accessToken) return; const task = setTimeout(() => { setLoading(true); void Promise.all([fetchAttendanceRoster(course.id, accessToken), fetchAttendanceSessions(course.id, accessToken)]).then(([students, attendance]) => { setRoster(students); setSessions(attendance); setAttendanceSessionId(attendance[0]?.id); }).catch((error: Error) => showToast.error('Could not load class data', error.message)).finally(() => setLoading(false)); }, 0); return () => clearTimeout(task); }, [visible, course, accessToken]);
  const save = async () => { const max = Number(maxScore); if (!course || !accessToken || !title.trim() || !Number.isFinite(max) || max <= 0) { showToast.error('Check assessment details', 'Add a title and a valid maximum score.'); return; } if (type === 'exam' && !attendanceSessionId) { showToast.error('Select attendance', 'Link the attendance session used for this exam.'); return; } const entries = roster.flatMap((student) => { const raw = scores[student.membership_id]?.trim(); return raw === '' || raw == null ? [] : [{ student_membership_id: student.membership_id, raw_score: Number(raw) }]; }); if (entries.some((entry) => !Number.isFinite(entry.raw_score) || entry.raw_score < 0 || entry.raw_score > max)) { showToast.error('Check scores', `Scores must be between 0 and ${max}.`); return; } setSaving(true); try { await createMarkSubmission({ class_id: course.id, assessment_name: title.trim(), assessment_type: type, max_score: max, attendance_session_id: type === 'exam' ? attendanceSessionId : undefined, entries }, accessToken); showToast.success('Marks saved', `${entries.length} student mark${entries.length === 1 ? '' : 's'} recorded.`); onClose(); onCreated(); } catch (error) { const message = error instanceof Error ? error.message : 'Could not save marks'; showToast.error('Marks not saved', message); } finally { setSaving(false); } };
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View className="flex-1 bg-mist dark:bg-bg-dark"><View className="px-5 pt-16 pb-4 bg-surface dark:bg-surface-dark flex-row items-center border-b border-border dark:border-border-dark"><TouchableOpacity onPress={onClose} className="w-10 h-10 items-center justify-center"><Ionicons name="close" size={24} color="#0f172a" /></TouchableOpacity><View className="flex-1"><ThemedText variant="heading">Enter marks</ThemedText><ThemedText variant="tiny">{course ? `${course.course_code} · ${course.section}` : 'Select a course first'}</ThemedText></View></View><ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 48 }}><TextInput value={title} onChangeText={setTitle} placeholder="Assessment title (e.g. CA 1)" placeholderTextColor="#64748b" className="rounded-2xl bg-surface dark:bg-surface-dark border border-border dark:border-border-dark px-4 py-4 text-text dark:text-text-dark" /><View className="flex-row gap-2 mt-3">{TYPES.map((item) => <TouchableOpacity key={item} onPress={() => setType(item)} className={`rounded-xl px-3 py-2 ${type === item ? 'bg-ocean' : 'bg-surface dark:bg-surface-dark border border-border dark:border-border-dark'}`}><ThemedText variant="tiny" className={type === item ? 'text-white font-bold' : ''}>{item}</ThemedText></TouchableOpacity>)}</View><View className="mt-4 rounded-2xl bg-surface dark:bg-surface-dark border border-border dark:border-border-dark p-4"><ThemedText variant="tiny">MAXIMUM SCORE</ThemedText><TextInput value={maxScore} onChangeText={setMaxScore} keyboardType="decimal-pad" className="text-text dark:text-text-dark text-2xl font-bold mt-1" /></View><ThemedText variant="subheading" className="mt-6 mb-2">Student scores</ThemedText>{loading ? <ActivityIndicator color="#0f766e" /> : roster.map((student) => <View key={student.membership_id} className="py-3 flex-row items-center border-b border-border dark:border-border-dark"><View className="w-9 h-9 rounded-full bg-ocean-soft items-center justify-center mr-3"><Ionicons name="person" size={17} color="#0f766e" /></View><ThemedText variant="caption" className="flex-1">{student.full_name}</ThemedText><TextInput value={scores[student.membership_id] ?? ''} onChangeText={(value) => setScores((all) => ({ ...all, [student.membership_id]: value }))} keyboardType="decimal-pad" placeholder="—" placeholderTextColor="#64748b" className="w-16 rounded-xl bg-surface dark:bg-surface-dark border border-border dark:border-border-dark px-2 py-2 text-center text-text dark:text-text-dark" /></View>)}<TouchableOpacity disabled={saving || !course} onPress={() => void save()} className="mt-7 rounded-2xl bg-ocean py-4 items-center"><ThemedText variant="body" className="text-white font-bold">{saving ? 'Saving…' : 'Save marks'}</ThemedText></TouchableOpacity></ScrollView></View></Modal>;
}
